services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://wallet_user:wallet_pass@db:5432/wallet_db?sslmode=disable

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"